version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: myawsdockerrepo
    IMAGE_TAG: 1.0
  parameter-store:
    LOGIN_PASSWORD: /Codebuild/DockerPassword

phases:
  pre_build:
    commands:
      - echo login in to docker
      - docker login -u gorairakesh -p $LOGIN_PASSWORD
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - printenv
      - echo starting docker daemon
      - systemctl start docker
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $IMAGE_REPO_NAME:$IMAGE_TAG