version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: myawsdockerrepo
    IMAGE_TAG: 1.0
  parameter-store:
    LOGIN_PASSWORD: /Codebuild/DockerPassword
    LOGIN_ID: /Codebuild/DockerLoginID

phases:
  pre_build:
    commands:
      - echo login in to docker
      - docker login -u $LOGIN_ID -p $LOGIN_PASSWORD
      - printenv
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $IMAGE_REPO_NAME:$IMAGE_TAG